site_name: TeamTV Api

# TODO: set-up Google Analytics project to track
google_analytics: null

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Backend API:
    - Intro/Authentication: backend_api/intro.md
    - ResourceGroup: backend_api/resource_group.md
    - SportingEvent: backend_api/sporting_event.md
    - EventStream: backend_api/event_stream.md
    - Studio: backend_api/studio.md
    - vMix: backend_api/vmix.md
    - Tokens: backend_api/tokens.md
  - Embedding: embedding.md
  - Frontend API: frontend_api.md

#  - Frontend API:
#    - Embedding: frontend_api/embedding.md
#    - Methods: frontend_api/methods.md
  - Webhooks: webhooks.md

#
#markdown_extensions:
#  - pymdownx.highlight:
#      use_pygments: true
#      linenums: true
#      linenums_style: table