site_name: TeamTV Api

# TODO: set-up Google Analytics project to track
google_analytics: null

theme:
  name: material

nav:
  - Home: index.md
  - Backend API:
    - Intro/Authentication: backend_api/intro.md
    - Resources:
      - ResourceGroup: backend_api/resource_group.md
      - Person: backend_api/person.md
      - Team: backend_api/team.md
      - Player: backend_api/player.md
      - SportingEvent: backend_api/sporting_event.md
      - Course: backend_api/course.md
      - Sponsor: backend_api/sponsor.md
    - Integrations:
      - EventStream: backend_api/event_stream.md
      - Studio: backend_api/studio.md
      - vMix: backend_api/vmix.md
    - Tokens: backend_api/tokens.md
    - Webhooks: webhooks.md
  - Frontend API:
    - Embedding: embedding.md

#  - Frontend API:
#    - Embedding: frontend_api/embedding.md
#    - Methods: frontend_api/methods.md


#
#markdown_extensions:
#  - pymdownx.highlight:
#      use_pygments: true
#      linenums: true
#      linenums_style: table